/* lcc generated prototype file. Do not edit */
#ifndef __glmvector_h__
#define __glmvector_h__

extern const float  GLM_ORIGIN_2F[2];
extern const double GLM_ORIGIN_2D[2];
extern const float  GLM_ORIGIN_3F[3];
extern const double GLM_ORIGIN_3D[3];
extern const float  GLM_ORIGIN_4F[4];
extern const double GLM_ORIGIN_4D[4];

#ifdef __cplusplus
extern "C" {
#endif
	
void glmCopyVector2f(const float *, float *);
void glmCopyVector2d(const double *, double *);
void glmCopyVector3f(const float *, float *);
void glmCopyVector3d(const double *, double *);
void glmCopyVector4f(const float *, float *);
void glmCopyVector4d(const double *, double *);
void glmCopyVectorf(const float *, float *, unsigned long);
void glmCopyVectord(const double *, double *, unsigned long);
void glmMakeVector2f(float *, const float *, const float *);
void glmMakeVector2d(double *, const double *, const double *);
void glmMakeVector3f(float *, const float *, const float *);
void glmMakeVector3d(double *, const double *, const double *);
void glmMakeVector4f(float *, const float *, const float *);
void glmMakeVector4d(double *, const double *, const double *);
void glmMakeVectorf(float *, const float *, const float *, unsigned long);
void glmMakeVectord(double *, const double *, const double *, unsigned long);
float glmDotProduct2f(const float *, const float *);
double glmDotProduct2d(const double *, const double *);
float glmDotProduct3f(const float *, const float *);
double glmDotProduct3d(const double *, const double *);
float glmDotProduct4f(const float *, const float *);
float glmDotProduct4d(const double *, const double *);
float glmDotProductf(const float *, const float *, unsigned long);
double glmDotProductd(const double *, const double *, unsigned long);
void glmCrossProduct2f(float *, const float *);
void glmCrossProduct2d(double *, const double *);
void glmCrossProduct3f(float *, const float *, const float *);
void glmCrossProduct3d(double *, const double *, const double *);
void glmCrossProduct4f(float *, const float *, const float *, const float *);
void glmCrossProduct4d(double *, const double *, const double *, const double *);
float glmNormalizeVector2f(float *);
double glmNormalizeVector2d(double *);
float glmNormalizeVector3f(float *);
double glmNormalizeVector3d(double *);
float glmNormalizeVector4f(float *);
double glmNormalizeVector4d(double *);
float glmNormalizeVectorf(float *, unsigned long);
double glmNormalizeVectord(double *, unsigned long);
float glmComputeVectorLength2f(const float *);
double glmComputeVectorLength2d(const double *);
float glmComputeVectorLength3f(const float *);
double glmComputeVectorLength3d(const double *);
float glmComputeVectorLength4f(const float *);
double glmComputeVectorLength4d(const double *);
float glmComputeVectorLengthf(const float *, unsigned long);
double glmComputeVectorLengthd(const double *, unsigned long);
float glmComputeVectorLength2fPow2(const float *);
double glmComputeVectorLength2dPow2(const double *);
float glmComputeVectorLength3fPow2(const float *);
double glmComputeVectorLength3dPow2(const double *);
float glmComputeVectorLength4fPow2(const float *);
double glmComputeVectorLength4dPow2(const float *);
float glmComputeVectorLengthfPow2(const float *, unsigned long);
double glmComputeVectorLengthdPow2(const double *, unsigned long);
float glmComputeNormalizedVectorAngle2fRad(const float *, const float *);
float glmComputeNormalizedVectorAngle2fDeg(const float *, const float *);
double glmComputeNormalizedVectorAngle2dRad(const double *, const double *);
double glmComputeNormalizedVectorAngle2dDeg(const double *, const double *);
float glmComputeNormalizedVectorAngle3fRad(const float *, const float *);
float glmComputeNormalizedVectorAngle3fDeg(const float *, const float *);
double glmComputeNormalizedVectorAngle3dRad(const double *, const double *);
double glmComputeNormalizedVectorAngle3dDeg(const double *, const double *);
float glmComputeNormalizedVectorAngle4fRad(const float *, const float *);
double glmComputeNormalizedVectorAngle4dRad(const double *, const double *);
float glmComputeNormalizedVectorAngle4fDeg(const float *, const float *);
double glmComputeNormalizedVectorAngle4dDeg(const double *, const double *);
float glmComputeNormalizedVectorAnglefRad(const float *, const float *, unsigned long);
float glmComputeNormalizedVectorAnglefDeg(const float *, const float *, unsigned long);
double glmComputeNormalizedVectorAngledRad(const double *, const double *, unsigned long);
double glmComputeNormalizedVectorAngledDeg(const double *, const double *, unsigned long);
float glmComputeVectorAngle2fRad(const float *, const float *);
float glmComputeVectorAngle2fDeg(const float *, const float *);
double glmComputeVectorAngle2dRad(const double *, const double *);
double glmComputeVectorAngle2dDeg(const double *, const double *);
float glmComputeVectorAngle3fRad(const float *, const float *);
float glmComputeVectorAngle3fDeg(const float *, const float *);
double glmComputeVectorAngle3dRad(const double *, const double *);
double glmComputeVectorAngle3dDeg(const double *, const double *);
float glmComputeVectorAngle4fRad(const float *, const float *);
float glmComputeVectorAngle4fDeg(const float *, const float *);
double glmComputeVectorAngle4dRad(const double *, const double *);
double glmComputeVectorAngle4dDeg(const double *, const double *);
float glmComputeVectorAnglefRad(const float *, const float *, unsigned long);
float glmComputeVectorAnglefDeg(const float *, const float *, unsigned long);
double glmComputeVectorAngledRad(const double *, const double *, unsigned long);
double glmComputeVectorAngledDeg(const double *, const double *, unsigned long);
void glmAddVector2f(float *, const float *, const float *);
void glmAddVector2d(double *, const double *, const double *);
void glmAddVector3f(float *, const float *, const float *);
void glmAddVector3d(double *, const double *, const double *);
void glmAddVector4f(float *, const float *, const float *);
void glmAddVector4d(double *, const double *, const double *);
void glmAddVectorf(float *, const float *, const float *, unsigned long);
void glmAddVectord(double *, const double *, const double *, unsigned long);
void glmSubtractVector2f(float *, const float *, const float *);
void glmSubtractVector2d(double *, const double *, const double *);
void glmSubtractVector3f(float *, const float *, const float *);
void glmSubtractVector3d(double *, const double *, const double *);
void glmSubtractVector4f(float *, const float *, const float *);
void glmSubtractVector4d(double *, const double *, const double *);
void glmSubtractVectorf(float *, const float *, const float *, unsigned long);
void glmSubtractVectord(double *, const double *, const double *, unsigned long);
void glmReflectVector2f(float *, const float *, const float *);
void glmReflectVector2d(double *, const double *, const double *);
void glmReflectVector3f(float *, const float *, const float *);
void glmReflectVector3d(double *, const double *, const double *);
void glmReflectVector4f(float *, const float *, const float *);
void glmReflectVector4d(double *, const double *, const double *);
void glmReflectVectorf(float *, const float *, const float *, unsigned long);
void glmReflectVectord(double *, const double *, const double *, unsigned long);
void glmGenerateRandomVector2f(float *);
void glmGenerateRandomVector2d(double *);
void glmGenerateRandomVector3f(float *);
void glmGenerateRandomVector3d(double *);
void glmComputeLineNormalf(float *, const float *, const float *);
void glmComputeLineNormald(double *, const double *, const double *);
void glmComputeTriangleNormalf(float *, const float *, const float *, const float *);
void glmComputeTriangleNormald(double *, const double *, const double *, const double *);
void glmMultVectorByScalar2f(float *, float);
void glmMultVectorByScalar2d(double *, double);
void glmMultVectorByScalar3f(float *, float);
void glmMultVectorByScalar4f(float *, float);
void glmMultVectorByScalar3d(double *, double);
void glmMultVectorByScalarf(float *, float, unsigned long);
void glmMultVectorByScalard(double *, double, unsigned long);
void glmProjectVector2f(float *, const float *, const float *);
void glmProjectVector2d(double *, const double *, const double *);
void glmProjectVector3f(float *, const float *, const float *);
void glmProjectVector3d(double *, const double *, const double *);
void glmPrintVector2f(const float *);
void glmPrintVector2d(const double *);
void glmPrintVector3f(const float *);
void glmPrintVector3d(const double *);
void glmPrintVector4f(const float *);
void glmPrintVector4d(const double *);
void glmPrintVectorf(const float *, unsigned long);
void glmPrintVectord(const double *, unsigned long);
void glmGenerateZeroVector2f(float *);
void glmGenerateZeroVector2d(double *);
void glmGenerateZeroVector3f(float *);
void glmGenerateZeroVector3d(double *);
void glmGenerateZeroVector4f(float *);
void glmGenerateZeroVector4d(double *);
void glmGenerateZeroVectorf(float *, unsigned long);
void glmGenerateZeroVectord(double *, unsigned long);
void glmColorFromVectorf(float *, const float *);
void glmColorFromVectord(double *, const double *);
void glmVectorFromColorf(float *, const float *);
void glmVectorFromColord(double *, const double *);
float glmComputeDistance2f(const float *, const float *);
double glmComputeDistance2d(const double *, const double *);
float glmComputeDistance3f(const float *, const float *);
double glmComputeDistance3d(const double *, const double *);
float glmComputeDistance4f(const float *, const float *);
double glmComputeDistance4d(const double *, const double *);
float glmComputeDistancef(const float *, const float *, unsigned long);
double glmComputeDistanced(const double *, const double *, unsigned long);
void glmReverseVector2f(float *);
void glmReverseVector2d(double *);
void glmReverseVector3f(float *);
void glmReverseVector3d(double *);
void glmReverseVector4f(float *);
void glmReverseVector4d(double *);
void glmReverseVectorf(float *, unsigned long);
void glmReverseVectord(double *, unsigned long);
void glmGenerateReverseVector2f(float *, const float *);
void glmGenerateReverseVector2d(double *, const double *);
void glmGenerateReverseVector3f(float *, const float *);
void glmGenerateReverseVector3d(double *, const double *);
void glmGenerateReverseVector4f(float *, const float *);
void glmGenerateReverseVector4d(double *, const double *);
void glmGenerateReverseVectorf(float *, const float *, unsigned long);
void glmGenerateReverseVectord(double *, const double *, unsigned long);
void glmInterpolateVector2f(float *, const float *, const float *, float);
void glmInterpolateVector2d(double *, const double *, const double *, double);
void glmInterpolateVector3f(float *, const float *, const float *, float);
void glmInterpolateVector3d(double *, const double *, const double *, double);
void glmInterpolateVector4f(float *, const float *, const float *, float);
void glmInterpolateVector4d(double *, const double *, const double *, double);
void glmInterpolateVectorf(float *, const float *, const float *, float, unsigned long);
void glmInterpolateVectord(double *, const double *, const double *, double, unsigned long);
int glmCompareVector2f(const float *, const float *);
int glmCompareVector2d(const double *, const double *);
int glmCompareVector3f(const float *, const float *);
int glmCompareVector3d(const double *, const double *);
int glmCompareVector4f(const float *, const float *);
int glmCompareVector4d(const double *, const double *);
int glmCompareVectorf(const float *, const float *, unsigned long);
int glmCompareVectord(const double *, const double *, unsigned long);
void glmComputeTriangleTangentsf(float *, float *, const float *, const float *, const float *, const float *, const float *, const float *);

#ifdef __cplusplus
}
#endif

#endif
